name: Azure pipeline

on:
  push:
    branches:
      - main

jobs:
  tf-run:
    name: Terraform run on Azure
    runs-on: ubuntu-latest

    steps:
      - name: Step 01 - CheckOut GitHub Repo
        uses: actions/checkout@v3

    #   - name: Step 02 - Azure Login
    #     run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    #   - name: Step 03 - Terraform Setup
    #     uses: hashicorp/setup-terraform@v2
    #     with:
    #       terraform_version: 1.5.0

    #   - name: Step 04 - Set Environment Variables for Service Principal Authentication
    #     env:
    #       TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
    #       TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
    #       TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #       TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
    #     run: echo "Environment variables set"

    #   - name: Step 05 - Terraform Init
    #     run: terraform -chdir=./terraform/ init -input=false

    #   - name: Step 06 - Terraform Validate
    #     run: terraform -chdir=./terraform/ validate

    #   - name: Step 07 - Terraform Plan
    #     run: terraform -chdir=./terraform/ plan -input=false -out tfplan

    #   - name: Step 08 - Terraform Show
    #     run: terraform -chdir=./terraform/ show
